#debug: true
server:  
  port: ${PORT:9090}
spring:
  aop:
    proxy-target-class: true
  application:
    name: zuul
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://ec2-3-120-208-177.eu-central-1.compute.amazonaws.com:8761/eureka/
    register-with-eureka: true
    fetch-registry: true



#ribbon: 
  #ReadTimeout: 60000
  #ConnectTimeout: 60000
#hystrix:
  #command:
    #default:
      #execution:
        #timeout:
          #enabled: false

hystrix:
  command.default.execution.timeout.enabled: false
  #Disable Hystrix timeout for a single service
  #command.<uac-service>.execution.timeout.enabled: false
  command.default.circuitBreaker.enabled: false
  command.default.fallback.enabled: false


zuul:
  routes:
    uaa:
      path: /uaa/**
      #url: http://192.168.0.157:9999
      sensitiveHeaders:
      stripPrefix: false
      